# Generated by Django 5.1.2 on 2024-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('PEI', 'Prince Edward Island')], max_length=3, null=True)),
                ('project_phase', models.CharField(choices=[('Planned', 'Planned'), ('Underway', 'Underway'), ('Complete', 'Complete')], max_length=10, null=True)),
                ('dwelling_type', models.CharField(choices=[('Single Family Unit', 'Single Family Unit'), ('Tiny Home', 'Tiny Home'), ('Micro Shelter', 'Micro Shelter')], max_length=20, null=True)),
                ('housing_model', models.CharField(choices=[('Co-operative', 'Co-operative'), ('Supportive Housing', 'Supportive Housing'), ('Other (Co-living)', 'Other (Co-living)'), ('Shelter', 'Shelter')], max_length=30, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('number_of_units', models.PositiveIntegerField(null=True)),
                ('project_partner_type', models.CharField(choices=[('Developer', 'Developer'), ('Other Partner', 'Other Partner'), ('Charitable Partner', 'Charitable Partner')], max_length=20, null=True)),
                ('partner_name', models.CharField(max_length=100, null=True)),
                ('demographic', models.CharField(max_length=100, null=True)),
                ('x_coordinate', models.FloatField(null=True)),
                ('y_coordinate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectListNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_units', models.CharField(blank=True, max_length=10, null=True)),
                ('dwelling_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_phase', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
