# Generated by Django 5.1.2 on 2024-10-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlistnews',
            name='summarize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
